#!/bin/bash

export TERM=xterm-256color

sgr() {
    local codes=${1:-0}; shift
    for c in "$@"; do codes="$codes;$c"; done
    echo -n -e "\e[${codes}m"
}
# Font styles
BOLD=$(sgr 1)
RED=$(sgr 31)
GREEN=$(sgr 38 5 2)
RST=$(sgr 0)

. /etc/turtleos_version
TNAME=$NAME
TVERSION=$VERSION

. /etc/os-release
DNAME=$NAME
DVERSION=$VERSION

UPTIME=$(uptime -p)
DATE=$(date +'%a %d %b %Y %T %Z')

clear
echo -e "               ------------------------------"
echo -e "               $(uname -rms) "
echo -e "$BOLD$GREEN $TNAME $TVERSION $RST $DNAME $DVERSION"
echo -e "               ------------------------------"
echo -e "               🕑 $DATE"
echo -e "               $UPTIME"
echo -e "              $GREEN Turtle Control Software $(tcs -v)$RST"
echo ""
